CREATE TABLE IF NOT EXISTS bl_3nf.ce_landings(
	LANDING_ID BIGINT NOT NULL,
	LANDING_SRC_ID VARCHAR(4000) NOT NULL,
	LANDING_NAME VARCHAR(4000) NOT NULL,
	INSERT_DT     DATE         NOT NULL,
    UPDATE_DT     DATE         NOT NULL,
    SOURCE_SYSTEM VARCHAR(4000) NOT NULL,
    SOURCE_ENTITY VARCHAR(4000) NOT NULL,
    CONSTRAINT pk_ce_landings PRIMARY KEY (LANDING_ID),
    
    CONSTRAINT uk_ce_landings_src
        UNIQUE (LANDING_SRC_ID, SOURCE_SYSTEM)
);
	
CREATE SEQUENCE IF NOT EXISTS bl_3nf.seq_ce_landings_id;


CREATE TABLE IF NOT EXISTS bl_3nf.ce_employees(
	EMPLOYEE_ID BIGINT NOT NULL,
	EMPLOYEE_SRC_ID VARCHAR(4000) NOT NULL,
	EMPLOYEE_ROLE VARCHAR(4000) NOT NULL,
	EMPLOYEE_YEARS INT NOT NULL,
	INSERT_DT     DATE         NOT NULL,
    UPDATE_DT     DATE         NOT NULL,
    SOURCE_SYSTEM VARCHAR(4000) NOT NULL,
    SOURCE_ENTITY VARCHAR(4000) NOT NULL,
    CONSTRAINT pk_ce_employees PRIMARY KEY (EMPLOYEE_ID),
    
    CONSTRAINT uk_ce_employees_src
        UNIQUE (EMPLOYEE_SRC_ID, SOURCE_SYSTEM)
);
	
CREATE SEQUENCE IF NOT EXISTS bl_3nf.seq_ce_employees_id;

CREATE TABLE IF NOT EXISTS bl_3nf.ce_products (
    PRODUCT_ID          BIGINT        NOT NULL,
    PRODUCT_SRC_ID      VARCHAR(4000) NOT NULL,
    PRODUCT_CATEGORY    VARCHAR(4000) NOT NULL,
    PRODUCT_SUBCATEGORY VARCHAR(4000) NOT NULL,
    PRODUCT_MATERIAL    VARCHAR(4000) NOT NULL,

    INSERT_DT           DATE          NOT NULL,
    UPDATE_DT           DATE          NOT NULL,
    SOURCE_SYSTEM       VARCHAR(4000) NOT NULL,
    SOURCE_ENTITY       VARCHAR(4000) NOT NULL,

    CONSTRAINT pk_ce_products
        PRIMARY KEY (PRODUCT_ID),

    CONSTRAINT uk_ce_products_src
        UNIQUE (PRODUCT_SRC_ID, SOURCE_SYSTEM)
);

CREATE SEQUENCE IF NOT EXISTS bl_3nf.seq_ce_products_id;

CREATE TABLE IF NOT EXISTS bl_3nf.ce_suppliers (
    SUPPLIER_ID        BIGINT        NOT NULL,
    SUPPLIER_SRC_ID    VARCHAR(4000) NOT NULL,
    SUPPLIER_COUNTRY   VARCHAR(4000) NOT NULL,
    SUPPLIER_SIZE      VARCHAR(4000) NOT NULL,

    INSERT_DT          DATE          NOT NULL,
    UPDATE_DT          DATE          NOT NULL,
    SOURCE_SYSTEM      VARCHAR(4000) NOT NULL,
    SOURCE_ENTITY      VARCHAR(4000) NOT NULL,

    CONSTRAINT pk_ce_suppliers
        PRIMARY KEY (SUPPLIER_ID),

    CONSTRAINT uk_ce_suppliers_src
        UNIQUE (SUPPLIER_SRC_ID, SOURCE_SYSTEM)
);

CREATE SEQUENCE IF NOT EXISTS bl_3nf.seq_ce_suppliers_id;

CREATE TABLE IF NOT EXISTS bl_3nf.ce_payments (
    PAYMENT_ID        BIGINT        NOT NULL,
    PAYMENT_SRC_ID    VARCHAR(4000) NOT NULL,
    PAYMENT_METHOD    VARCHAR(4000) NOT NULL,
    PAYMENT_STATUS    VARCHAR(4000) NOT NULL,
    PAYMENT_PROVIDER  VARCHAR(4000) NOT NULL,

    INSERT_DT         DATE          NOT NULL,
    UPDATE_DT         DATE          NOT NULL,
    SOURCE_SYSTEM     VARCHAR(4000) NOT NULL,
    SOURCE_ENTITY     VARCHAR(4000) NOT NULL,

    CONSTRAINT pk_ce_payments
        PRIMARY KEY (PAYMENT_ID),

    CONSTRAINT uk_ce_payments_src
        UNIQUE (PAYMENT_SRC_ID, SOURCE_SYSTEM)
);

CREATE SEQUENCE IF NOT EXISTS bl_3nf.seq_ce_payments_id;

CREATE TABLE IF NOT EXISTS bl_3nf.ce_deliveries (
    DELIVERY_ID         BIGINT        NOT NULL,
    DELIVERY_SRC_ID     VARCHAR(4000) NOT NULL,
    DELIVERY_ADDRESS    VARCHAR(4000) NOT NULL,

    INSERT_DT           DATE          NOT NULL,
    UPDATE_DT           DATE          NOT NULL,
    SOURCE_SYSTEM       VARCHAR(4000) NOT NULL,
    SOURCE_ENTITY       VARCHAR(4000) NOT NULL,

    CONSTRAINT pk_ce_deliveries
        PRIMARY KEY (DELIVERY_ID),

    CONSTRAINT uk_ce_deliveries_src
        UNIQUE (DELIVERY_SRC_ID, SOURCE_SYSTEM)
);

CREATE SEQUENCE IF NOT EXISTS bl_3nf.seq_ce_deliveries_id;



CREATE TABLE IF NOT EXISTS bl_3nf.ce_cities (
    CITY_ID         BIGINT        NOT NULL,
    CITY_SRC_ID     VARCHAR(4000) NOT NULL,
    CITY_NAME       VARCHAR(4000) NOT NULL,

    INSERT_DT       DATE          NOT NULL,
    UPDATE_DT       DATE          NOT NULL,
    SOURCE_SYSTEM   VARCHAR(4000) NOT NULL,
    SOURCE_ENTITY   VARCHAR(4000) NOT NULL,

    CONSTRAINT pk_ce_cities
        PRIMARY KEY (CITY_ID),

    CONSTRAINT uk_ce_cities_src
        UNIQUE (CITY_SRC_ID, SOURCE_SYSTEM)
);

CREATE SEQUENCE IF NOT EXISTS bl_3nf.seq_ce_cities_id;



CREATE TABLE IF NOT EXISTS bl_3nf.ce_districts (
    DISTRICT_ID       BIGINT        NOT NULL,
    DISTRICT_SRC_ID   VARCHAR(4000) NOT NULL,
    DISTRICT_NAME     VARCHAR(4000) NOT NULL,
    CITY_ID           BIGINT        NOT NULL,

    INSERT_DT         DATE          NOT NULL,
    UPDATE_DT         DATE          NOT NULL,
    SOURCE_SYSTEM     VARCHAR(4000) NOT NULL,
    SOURCE_ENTITY     VARCHAR(4000) NOT NULL,

    CONSTRAINT pk_ce_districts
        PRIMARY KEY (DISTRICT_ID),

    CONSTRAINT uk_ce_districts_src
        UNIQUE (DISTRICT_SRC_ID, SOURCE_SYSTEM),

    CONSTRAINT fk_ce_districts_city
        FOREIGN KEY (CITY_ID)
        REFERENCES bl_3nf.ce_cities (CITY_ID)
);

CREATE SEQUENCE IF NOT EXISTS bl_3nf.seq_ce_districts_id;


CREATE TABLE IF NOT EXISTS bl_3nf.ce_stores (
    STORE_ID         BIGINT        NOT NULL,
    STORE_SRC_ID     VARCHAR(4000) NOT NULL,
    STORE_BRAND      VARCHAR(4000) NOT NULL,
    DISTRICT_ID      BIGINT        NOT NULL,

    INSERT_DT        DATE          NOT NULL,
    UPDATE_DT        DATE          NOT NULL,
    SOURCE_SYSTEM    VARCHAR(4000) NOT NULL,
    SOURCE_ENTITY    VARCHAR(4000) NOT NULL,

    CONSTRAINT pk_ce_stores
        PRIMARY KEY (STORE_ID),

    CONSTRAINT uk_ce_stores_src
        UNIQUE (STORE_SRC_ID, SOURCE_SYSTEM),

    CONSTRAINT fk_ce_stores_district
        FOREIGN KEY (DISTRICT_ID)
        REFERENCES bl_3nf.ce_districts (DISTRICT_ID)
);

CREATE SEQUENCE IF NOT EXISTS bl_3nf.seq_ce_stores_id;

CREATE TABLE IF NOT EXISTS bl_3nf.ce_customers_scd (
    CUSTOMER_ID BIGINT NOT NULL,
    CUSTOMER_SRC_ID BIGINT NOT NULL,

    CUSTOMER_GENDER VARCHAR(4000) NOT NULL,
    CUSTOMER_AGE INT NOT NULL,
    CUSTOMER_SEGMENT VARCHAR(4000) NOT NULL,
    REGISTERED_CUSTOMER BOOLEAN NOT NULL DEFAULT FALSE,
    CUSTOMER_REGISTRATION_DATE DATE NOT NULL,

    START_DT DATE NOT NULL DEFAULT DATE '1990-01-01',
    END_DT DATE NOT NULL DEFAULT DATE '9999-12-31',
    IS_ACTIVE VARCHAR(1) NOT NULL DEFAULT 'Y',

    SOURCE_SYSTEM VARCHAR(4000) NOT NULL,
    SOURCE_ENTITY VARCHAR(4000) NOT NULL,

    INSERT_DT TIMESTAMP NOT NULL,
    UPDATE_DT TIMESTAMP NOT NULL,

    CONSTRAINT pk_ce_customers_scd
        PRIMARY KEY (CUSTOMER_ID, START_DT),

    CONSTRAINT uk_ce_customers_scd_src
        UNIQUE (CUSTOMER_SRC_ID, SOURCE_SYSTEM, START_DT),

    CONSTRAINT chk_ce_customers_scd_is_active
        CHECK (IS_ACTIVE IN ('Y','N'))
);

CREATE SEQUENCE IF NOT EXISTS bl_3nf.seq_ce_customers_id;

CREATE TABLE IF NOT EXISTS bl_3nf.ce_sales (
    SALES_ID BIGINT NOT NULL,
    TRANSACTION_SRC_ID BIGINT NOT NULL,

    PRODUCT_ID BIGINT NOT NULL,
    SUPPLIER_ID BIGINT NOT NULL,
    CUSTOMER_ID BIGINT NOT NULL,
    STORE_ID BIGINT NOT NULL,
    EMPLOYEE_ID BIGINT NOT NULL,
    DELIVERY_ID BIGINT NOT NULL,
    LANDING_ID BIGINT NOT NULL,
    PAYMENT_ID BIGINT NOT NULL,

    SALE_DATE DATE NOT NULL,

    PRICE_RETAIL NUMERIC NOT NULL,
    PRICE_DISCOUNT NUMERIC NOT NULL,
    PRICE_SALE NUMERIC NOT NULL,
    PRODUCT_COST NUMERIC NOT NULL,
    I_DELIVERED_IN INT NOT NULL,

    SOURCE_SYSTEM VARCHAR(4000) NOT NULL,
    SOURCE_ENTITY VARCHAR(4000) NOT NULL,

    INSERT_DT TIMESTAMP NOT NULL,
    UPDATE_DT TIMESTAMP NOT NULL,

    CONSTRAINT pk_ce_sales
        PRIMARY KEY (SALES_ID),

    CONSTRAINT uk_ce_sales_src
        UNIQUE (TRANSACTION_SRC_ID, SOURCE_SYSTEM),

    CONSTRAINT fk_ce_sales_product
        FOREIGN KEY (PRODUCT_ID)
        REFERENCES bl_3nf.ce_products (PRODUCT_ID),

    CONSTRAINT fk_ce_sales_supplier
        FOREIGN KEY (SUPPLIER_ID)
        REFERENCES bl_3nf.ce_suppliers (SUPPLIER_ID),

    CONSTRAINT fk_ce_sales_store
        FOREIGN KEY (STORE_ID)
        REFERENCES bl_3nf.ce_stores (STORE_ID),

    CONSTRAINT fk_ce_sales_employee
        FOREIGN KEY (EMPLOYEE_ID)
        REFERENCES bl_3nf.ce_employees (EMPLOYEE_ID),

    CONSTRAINT fk_ce_sales_delivery
        FOREIGN KEY (DELIVERY_ID)
        REFERENCES bl_3nf.ce_deliveries (DELIVERY_ID),

    CONSTRAINT fk_ce_sales_payment
        FOREIGN KEY (PAYMENT_ID)
        REFERENCES bl_3nf.ce_payments (PAYMENT_ID),

    CONSTRAINT fk_ce_sales_landing
        FOREIGN KEY (LANDING_ID)
        REFERENCES bl_3nf.ce_landings (LANDING_ID)

    -- NO FK to CE_CUSTOMERS_SCD (SCD2 rule)
);

CREATE SEQUENCE IF NOT EXISTS bl_3nf.seq_ce_sales_id;