--2.1)
CREATE SCHEMA labs


SHOW SEARCH_path
RESET SEARCH_path

SET search_path TO labs;

CREATE TABLE labs.person (
id integer NOT NULL,
name varchar(15)
);
INSERT INTO person VALUES(1, 'Bob');
INSERT INTO person VALUES(2, 'Alice');
INSERT INTO person VALUES(3, 'Robert');

--2)
--unlogged tables

CREATE TABLE labs.test_simple (
a int,
b int
);

EXPLAIN analyze
insert into test_simple values (generate_series(1,1000000));
--Planning Time: 0.927 ms
--Execution Time: 1509.472 ms

EXPLAIN ANALYZE
insert into test_simple values (generate_series(1,5000000));
--Planning Time: 0.090 ms
--Execution Time: 7879.475 ms  -- took about 5x more time


CREATE UNLOGGED TABLE test_unlogged (
a int,
b int
);

EXPLAIN analyze
insert into test_unlogged values (generate_series(1,1000000));
--Planning Time: 0.037 ms
--Execution Time: 232.220 ms

EXPLAIN ANALYZE
insert into test_unlogged values (generate_series(1,5000000));
--Planning Time: 0.058 ms
--Execution Time: 1233.028 ms

--unlogged files skip WAL loggings, which are important for D in ACID, durability against accidents.
--Skipping WAL loggings 



--2.2)

DROP TABLE labs.users

CREATE TABLE IF NOT exists labs.users (
    user_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login VARCHAR(30)
) INHERITS (person);

INSERT INTO users (id, name, login)
VALUES (1, 'new Bob', 'NewLogin');

INSERT INTO users (id, name, login)
VALUES (999, 'TestUser', 'TestLogin');

SELECT * FROM users;
SELECT * FROM person;
SELECT * FROM ONLY person;

UPDATE person
SET name = 'not Bob'
where id = 1;

UPDATE ONLY person
SET name = 'not not Bob'
where id = 1;

ALTER TABLE person ADD COLUMN status integer DEFAULT 0;
ALTER TABLE person ADD CONSTRAINT status CHECK (status in (0,1))

UPDATE person
SET status = '5'
where id = 999;

ALTER TABLE person ADD CONSTRAINT id UNIQUE (id, name);





--3.1)

CREATE TABLE labs.test_index (
num float NOT NULL,
load_date timestamptz NOT NULL
);

INSERT INTO test_index(num, load_date)
SELECT random(), x
FROM generate_series('2017-01-01 0:00'::timestamptz,
'2021-12-31 23:59:59'::timestamptz, '10 seconds'::interval) x;

SELECT pg_size_pretty(pg_relation_size('test_index'));

SELECT count(*)
FROM test_index

EXPLAIN analyze
SELECT date_trunc('year', load_date), max(num)
FROM test_index
WHERE load_date BETWEEN '2021-09-01 0:00' AND '2021-10-31 11:59:59'
GROUP BY 1
ORDER BY 1;

CREATE INDEX idx_test_index_load_date
ON labs.test_index (load_date);
-- again
EXPLAIN ANALYZE
SELECT date_trunc('year', load_date), max(num)
FROM test_index
WHERE load_date BETWEEN '2021-09-01 0:00'
                    AND '2021-10-31 11:59:59'
GROUP BY 1
ORDER BY 1;

SELECT pg_size_pretty(
       pg_relation_size('idx_test_index_load_date')
);

SELECT pg_size_pretty(
       pg_total_relation_size('test_index')
);
DROP INDEX idx_test_index_load_date

CREATE INDEX idx_test_index_load_date_brin
ON labs.test_index
USING BRIN (load_date);
--and once more
EXPLAIN ANALYZE
SELECT date_trunc('year', load_date), max(num)
FROM test_index
WHERE load_date BETWEEN '2021-09-01 0:00'
                    AND '2021-10-31 11:59:59'
GROUP BY 1
ORDER BY 1;

SELECT pg_size_pretty(
       pg_relation_size('idx_test_index_load_date_brin')
);

DROP TABLE test_index


--3.2)

CREATE TABLE test_index AS SELECT id, md5(id::text) as t_hash
FROM generate_series(1, 10000000) AS id;

SELECT pg_size_pretty(
       pg_total_relation_size('test_index')
);

EXPLAIN analyze
SELECT * FROM test_index
WHERE t_hash LIKE '%ceea167a5a%';

CREATE EXTENSION pg_trgm;

CREATE INDEX idx_text_index_gist ON test_index USING gist(t_hash
gist_trgm_ops);

SELECT pg_size_pretty(pg_relation_size('test_index'));

DROP INDEX idx_text_index_gist;

CREATE INDEX idx_text_index_gin
ON test_index
USING gin (t_hash gin_trgm_ops);

SELECT pg_size_pretty(
       pg_relation_size('idx_text_index_gin')
);

EXPLAIN ANALYZE
SELECT *
FROM test_index
WHERE t_hash LIKE '%ceea167a5a%';

DROP TABLE test_index;
DROP INDEX idx_text_index_gin;


--4.1)
CREATE EXTENSION file_fdw;
CREATE SERVER test_import FOREIGN DATA WRAPPER file_fdw;

CREATE FOREIGN TABLE labs.test_foreign_table
(
LatD INT,
LatM INT,
LatS INT,
NS TEXT,
LonD INT,
LonM INT,
LonS INT,
EW TEXT,
City TEXT,
State TEXT
)
SERVER test_import
OPTIONS
(
filename '/tmp/cities_list.csv',
format 'csv',
header 'true',
delimiter ','
);

SELECT *
FROM labs.test_foreign_table
LIMIT 10

SELECT count(*) FROM labs.test_foreign_table;


CREATE MATERIALIZED VIEW labs.mview AS
SELECT *
FROM labs.test_foreign_table;

SELECT count(*) FROM labs.mview;
SELECT count(*) FROM labs.test_foreign_table;

REFRESH MATERIALIZED VIEW labs.mview;
SELECT count(*) FROM labs.test_foreign_table;
